FROM wngn123/centos:latest

MAINTAINER wngn123 wngn123@163.com

ADD jdk.tar.gz /usr/local

RUN ln -s /usr/local/jdk/bin/java /bin/java \
    && ln -s /usr/local/jdk/bin/jcontrol /bin/jcontrol \
	&& ln -s /usr/local/jdk/bin/javaws /bin/javaws \
	&& ln -s /usr/local/jdk/bin/jjs /bin/jjs \
	&& ln -s /usr/local/jdk/bin/keytool /bin/keytool
 
ENV JAVA_HOME /usr/local/jdk
ENV PATH $PATH:$JAVA_HOME/bin

CMD ["/bin/bash"]