FROM wngn123/centos:latest

MAINTAINER wngn123 wngn123@163.com

ADD jdk-8u191-linux-x64.tar.gz /usr/local/jdk

RUN mv /usr/local/jdk/jdk1.8.0_191/* /usr/local/jdk/ \
    && rm -rf /usr/local/jdk/jdk1.8.0_191 \
    && ln -s /usr/local/jdk/bin/java /bin/java

ENV JAVA_HOME /usr/local/jdk
ENV PATH $PATH:$JAVA_HOME/bin

CMD ["/bin/bash"]